[tool.poetry]
name = "src"
version = "0.1.0"
description = "Python example project"
authors = []

[tool.poetry.dependencies]
python = "^3.14"
pytest = "^8.3.5"
pillow = "12.0.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
